// ESPHome Designer Configuration
// This file is auto-generated by docker-entrypoint.sh when running in Docker.
// When running outside Docker, this placeholder prevents 404 errors.
// Environment variables (HA_URL, HA_TOKEN) will be injected at container startup.
window.ESPHOME_DESIGNER_CONFIG = {
    HA_URL: "",
    HA_TOKEN: ""
};
